Repository thong-dipro/API-Petshop, pull requests merged in 2022-10, with the labels that each got.

#16 [Feat] All Model Complete
  controllers/productController.js
  database/models/addressModel.js
  database/models/assetsModel.js
  database/models/categoryModel.js
  database/models/districtModel.js
  database/models/feedbackModel.js
  database/models/feedbackReplyModel.js
  database/models/proviceModel.js
  database/models/townModel.js
  database/models/typeModel.js
  database/models/userModel.js
Labels: feat

#18 [Feat] Handle auth token
  app.js
  controllers/userController.js
  middlewares/authJWT.js
  middlewares/verifyJWT.js
  routes/userRouter.js
Labels: feat, user

#19 Complete function's Type
  app.js
  controllers/assetsController.js
  controllers/orderController.js
  controllers/typeController.js
  database/models/orderItemModel.js
  database/models/orderModel.js
  database/models/productModel.js
  database/models/statusModel.js
  routes/assetsRouter.js
  routes/orderRouter.js
  routes/typeRouter.js
Labels: feat, type

#25 update pakage
  package.json
Labels: feat

#26 Fix User Model
  database/models/userModel.js
Labels: good first issue, user
